version: '3'
services:
  postgres:
    image: "postgres"
    ports:
      - "${POSTGRESQL_PORT}:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - nw

  minio:
    image: minio/minio
    command: server --console-address :9001 /data
    ports:
      - "${MINIO_PORT}:9000/tcp"
      - "${MINIO_GUI_PORT}:9001/tcp"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    networks:
      nw:

  minio-provision:
    build:
      context: demo/s3/provision
    volumes:
      - ./demo/s3/posters/:/posters/
    networks:
      - nw

volumes:
  pg-data:
  minio-data:

networks:
  nw:
