server:
  port: 9900
  forward-headers-strategy: native

spring:
  application:
    name: gateway
  cloud:
    gateway:
      loadbalancer:
        use404: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
            allowCredentials: false
            maxAge: 1800
      routes:
        - id: backend
          uri: lb://backend
          predicates:
            - Path=/backend/**
          filters:
            - RewritePath=/backend/(?<segment>.*), /$\{segment}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.int(1000)}}}

management:
  endpoints:
    web:
      exposure:
        include: info,metrics,health,prometheus
  endpoint:
    health:
      show-components: always
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true