global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s
# scrape metrics from the prometheus server itself
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  # Discover targets from Eureka and scrape metrics from them (Whitebox monitoring)
  - job_name: eureka-dev
    scrape_interval: 5s
    scrape_timeout: 5s
    eureka_sd_configs:
      - server: http://192.168.254.50:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
      - source_labels: [ __metrics_path__ ]
        replacement: /actuator/prometheus
        target_label: __metrics_path__

  - job_name: eureka-docker
    scrape_interval: 5s
    scrape_timeout: 5s
    eureka_sd_configs:
      - server: http://eureka:8761/eureka
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
      - source_labels: [ __metrics_path__ ]
        replacement: /actuator/prometheus
        target_label: __metrics_path__
